Met
sul-dlss/dlme-transform pull request #698
Opened 2021-06-10 20:22 UTC by jacobthill

## Why was this change made?

revise Met mapping

## How was this change tested?

local transform and load in dev

## Which documentation and/or configurations were updated?

n/a

2021-06-11 16:03 UTC, aaron-collier requested changes
Just a few comments/questions.

2021-06-11 16:03 UTC, aaron-collier commented on lib/macros/title_extraction.rb
> +        acc.replace(["#{title} #{truncate(other)}"]) if title.present? && other.present?
Since both of these rely on `other.present?` I think it would be preferable to do something like:

```
if other.present?
  title.present? ? acc.replace(["#{title} #{truncate(other)}"]) : acc.replace([truncate(other)])
end
```

2021-06-11 16:03 UTC, aaron-collier commented on lib/macros/title_extraction.rb
> +        acc.replace(["#{title} #{truncate(other)}"]) if title.present? && other.present?
Same as above here.

2021-06-11 16:03 UTC, aaron-collier commented on traject_configs/met_config.rb
> +require 'macros/string_helper'
Are these 2 requires necessary? I'm not seeing them used (though could just be missing them)

2021-06-11 16:55 UTC, jacobthill commented on lib/macros/title_extraction.rb
> +        acc.replace(["#{title} #{truncate(other)}"]) if title.present? && other.present?
Thanks, that a new syntax for me.

2021-06-17 18:08 UTC, jacobthill commented on traject_configs/met_config.rb
> +require 'macros/string_helper'
`squish` is from `string_helper`. I know there is a rails method that does the same thing but I paired with John Martin to figure out how to use it and neither of us could figure out why it wasn't available. So we did this. I was missing the path_to_file but fixing in a follow up commit.

2021-06-22 16:37 UTC, aaron-collier approved these changes

2021-06-22 16:37 UTC, merged