add translations
sul-dlss/dlme-transform pull request #787
Opened 2021-08-11 17:17 UTC by jacobthill

## Why was this change made?

- Add new Arabic translations
- Un-comment translation map tests

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-08-12 13:51 UTC, jacobthill commented
@aaron-collier I tried to rebase this but I think I added some changes that weren't supposed to be added. I don't want to make it worse. Can you fix this please?

2021-08-17 16:19 UTC, jmartin-sul requested changes
a couple questions about changes to the translation maps, not sure if typos in translation maps or if typos upstream being accounted for by translation maps.  and one question about a removed TODO that seemed like maybe it should've stayed.

the "request changes" is more about the TODO, since i wasn't sure whether i'd noticed an actual problem with the translations.

2021-08-17 16:19 UTC, jmartin-sul commented on lib/translation_maps/edm_type_from_has_type.yaml
> +Rablets: Object
`Rablets` -> `Tablets`?

2021-08-17 16:19 UTC, jmartin-sul commented on lib/translation_maps/edm_type_from_has_type.yaml
> +Rablets: Object
ah, i see `Tablets` is in the list too, so maybe this translation is for a typo in the source data?

2021-08-17 16:19 UTC, jmartin-sul commented on spec/lib/translation_maps/validate_contributor_translation_maps_spec.rb
> -  # TODO: un-skip once we have the translations that will make it pass. see https://github.com/sul-dlss/dlme-transform/issues/738
should this TODO have stayed since the `it_behaves_like` below is still commented out?

2021-08-17 16:21 UTC, aaron-collier commented on spec/lib/translation_maps/validate_contributor_translation_maps_spec.rb
> -  # TODO: un-skip once we have the translations that will make it pass. see https://github.com/sul-dlss/dlme-transform/issues/738
Just noticed I missed that one. commit incoming.

2021-08-17 16:21 UTC, aaron-collier commented on lib/translation_maps/edm_type_from_has_type.yaml
> +Rablets: Object
Ah - I totally missed `Rablets` and added `Tablets` - good catch.

2021-08-17 16:27 UTC, aaron-collier commented on spec/lib/translation_maps/validate_contributor_translation_maps_spec.rb
> -  # TODO: un-skip once we have the translations that will make it pass. see https://github.com/sul-dlss/dlme-transform/issues/738
I was supposed to also uncomment the test on line 28 (whoops).

2021-08-17 17:20 UTC, jmartin-sul approved these changes

2021-08-17 17:20 UTC, merged